kind: Pod
apiVersion: v1
metadata:
  name: testpod-1
spec:
  nodeSelector:
    node-role.kubernetes.io/edge: ""
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: my-csi-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: my-csi-volume
      persistentVolumeClaim:
        claimName: csi-hostpath-pvc
---
kind: Pod
apiVersion: v1
metadata:
  name: testpod-2
spec:
  nodeSelector:
    node-role.kubernetes.io/edge: ""
  containers:
    - name: my-frontend
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: my-csi-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: my-csi-volume
      persistentVolumeClaim:
        claimName: csi-hostpath-pvc-2